name: CI/CD

on:
  push:
    branches: [ main ]

env:
  APP_NAME: Caulius

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        
    - name: Test
      run: |
        dotnet test --no-restore --verbosity normal
        
    - name: Publish
      run: |
        dotnet publish --configuration Release --runtime win-x64 --self-contained true --output './output'

    - name: Zip Artifact
      run: |
        zip -r 'artifact.zip' './output/'

    - name: Deploy to Azure
      run: |
        curl --location --request PUT '${{ secrets.SCM_API_URL }}/continuouswebjobs/${{ env.APP_NAME }}' \
        --header "Authorization: Basic `echo -n '${{ secrets.DEPLOYMENT_USERNAME }}:${{ secrets.DEPLOYMENT_PASSWORD }}' | base64 -w 0`" \
        --header 'Content-Disposition: attachment; filename=artifact.zip' \
        --header 'Content-Type: application/zip' \
        --data-binary '@artifact.zip'
