name: Deploy Caulius

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BINARIES: './output/app_data/jobs/continuous/Caulius'
  ZIP_FILE: 'release.zip'
  ZIP_PATH: './output/'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore

    - name: Build and Publish
      run: |
        dotnet build --configuration Release --no-restore
        dotnet test --no-restore --verbosity normal
        dotnet publish --configuration Release --no-build --output ${{ env.BINARIES }}
        
    - name: Zip Artifact
      run: |
        zip -r ${{env.ZIP_FILE}} ${{env.ZIP_PATH}}
    
    - name: Deploy Continuous Web Job
      uses: srijken/azure-zip-deploy@v1.0.1
      with:
        zip-file: ${{env.ZIP_FILE}}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
