name: Deploy Caulius

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_PACKAGE_PATH: '.'
  APP_NAME: Caulius

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore

    - name: Build and Publish
      run: |
        dotnet build --configuration Release --no-restore
        dotnet test --no-restore --verbosity normal
        dotnet publish -o '${{ env.APP_PACKAGE_PATH }}/output'
      
    - name: Zip Artifact
      run: |
        zip -r '${{ env.APP_PACKAGE_PATH }}/output/artifact.zip' '${{ env.APP_PACKAGE_PATH }}/output/'
    
    - name: Deploy Continuous Web Job
      run: |
        curl --location --request PUT '${{ secrets.SCM_API_URL }}/continuouswebjobs/${{ env.APP_NAME }}' \
        --header "Authorization: Basic `echo -n '${{ secrets.DEPLOYMENT_USERNAME }}:${{ secrets.DEPLOYMENT_PASSWORD }}' | base64 -w 0`" \
        --header 'Content-Disposition: attachment; filename=artifact.zip' \
        --header 'Content-Type: application/zip' \
        --data-binary '@${{ env.APP_PACKAGE_PATH }}/output/artifact.zip'
